name: surplus4society
description: Surplus4Society - A Flutter app for managing surplus donations
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_data_connect: ^0.1.4
  flutter_lints: ^5.0.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.5.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
